
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action applyAction;

	private global::Gtk.VBox vbox5;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.TextView DbNameInput;

	private global::Gtk.Button BT_ConnectDB;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView InputTextView;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView OutputTextView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.applyAction = new global::Gtk.Action("applyAction", global::Mono.Unix.Catalog.GetString("exec"), null, "gtk-apply");
		this.applyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("exec");
		w1.Add(this.applyAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Homogeneous = true;
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'applyAction\' action=\'applyAction\'/><" +
				"/toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox6.Add(this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.DbNameInput = new global::Gtk.TextView();
		this.DbNameInput.CanFocus = true;
		this.DbNameInput.Name = "DbNameInput";
		this.hbox1.Add(this.DbNameInput);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.DbNameInput]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BT_ConnectDB = new global::Gtk.Button();
		this.BT_ConnectDB.CanFocus = true;
		this.BT_ConnectDB.Name = "BT_ConnectDB";
		this.BT_ConnectDB.UseUnderline = true;
		this.BT_ConnectDB.Label = global::Mono.Unix.Catalog.GetString("ConnectDB");
		this.hbox1.Add(this.BT_ConnectDB);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BT_ConnectDB]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox6.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.InputTextView = new global::Gtk.TextView();
		this.InputTextView.CanFocus = true;
		this.InputTextView.Name = "InputTextView";
		this.GtkScrolledWindow.Add(this.InputTextView);
		this.vbox6.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow]));
		w7.Position = 2;
		this.vbox5.Add(this.vbox6);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
		w8.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.OutputTextView = new global::Gtk.TextView();
		this.OutputTextView.CanFocus = true;
		this.OutputTextView.Name = "OutputTextView";
		this.OutputTextView.Editable = false;
		this.GtkScrolledWindow1.Add(this.OutputTextView);
		this.vbox5.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow1]));
		w10.Position = 1;
		this.Add(this.vbox5);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 898;
		this.DefaultHeight = 680;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.applyAction.Activated += new global::System.EventHandler(this.exec);
		this.BT_ConnectDB.Clicked += new global::System.EventHandler(this.hdConnectDB);
	}
}
